[application]
name = "Morphir Live"
default_platform = "desktop"
asset_dir = "assets"

[web.app]
# HTML title tag content
title = "Morphir Live"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[desktop]
# Desktop window configuration

[desktop.window]
title = "Morphir Live"
resizable = true
width = 1280
height = 800
